### ISSUE TITLE
Metric integrity in long-running applications.

### ISSUE THREAD

**Issue by jswrenn** [tokio-rs/tokio-metrics#4]
Is storing durations as u64 nanoseconds enough? It’s 584 years, but if you have 5000 tasks, you’ll burn through it in 42 days of uptime. That sounds doable. At minimum, we should make sure it doesn’t panic on overflow/underflow.

**Comment by Darksonn** [comment]
Our metrics are generally not tied to tasks, but to worker threads, and each worker thread has a separate counter, so it really should take 584 years to run out.

**Comment by jswrenn** [comment]
I was mostly concerned about task metrics. I [switched the calculation](https://github.com/tokio-rs/tokio-metrics/blob/e400acbdfdfd4c2d953efc8db84828d2f967883f/src/task.rs#L914-L929) of metrics deltas to use `wrapping_sub` to remove the potential for panics, and [documented/tested the accuracy limitations](https://github.com/tokio-rs/tokio-metrics/blob/e400acbdfdfd4c2d953efc8db84828d2f967883f/src/task.rs#L66-L216) of task metrics.
